#!/bin/bash

clear && rm -rf build && mkdir build;

gcc -c list/list.c -o build/list.o
gcc -c test/list_test.c -I./list -o build/test.o
gcc build/list.o build/test.o -lunity -o build/test

./build/test
